language: go
dist: bionic
sudo: required
go:
  - 1.15
env:
  - GO111MODULE=on

go_import_path: github.com/gothinkster/golang-gin-realworld-example-app

before_install:
  - sudo apt-get update
  - sudo apt-get install -y build-essential
install:
  - go mod download
  # - go get -u github.com/gothinkster/golang-gin-realworld-example-app
script:
  - go test -v ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
