language: go

go:
  - 1.10
  - master

go_import_path: github.com/macchiang/golang-gin-realworld-example-app

services:
  - sqlite3

install:
  - go get -u github.com/macchiang/golang-gin-realworld-example-app
script:
  #  - go test -v ./...
  - bash ./scripts/gofmt.sh
  - bash ./scripts/coverage.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
